repos:
  - repo: https://github.com/asottile/nbstripout
    rev: v0.5.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: [nbformat]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.2
    hooks:
      - id: isort
        additional_dependencies: [nbformat]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [nbformat]
