resources:
  jobs:
    New_Job_2024_04_05_02_20_53:
      name: New Job 2024-04-05 02:20:53
      tasks:
        - task_key: extract_raw_data
          notebook_task:
            notebook_path: /Repos/kapposev@outlook.com/assessment-rent-airbnb/src/extract_data
            source: WORKSPACE
          existing_cluster_id: 0403-201312-v0u48bii
        - task_key: test_bronze_data
          depends_on:
            - task_key: extract_raw_data
          notebook_task:
            notebook_path: /Repos/kapposev@outlook.com/assessment-rent-airbnb/src/tests/test_bronze_data_ingestion
            source: WORKSPACE
          existing_cluster_id: 0403-201312-v0u48bii
        - task_key: transform_data
          depends_on:
            - task_key: test_bronze_data
          notebook_task:
            notebook_path: /Repos/kapposev@outlook.com/assessment-rent-airbnb/src/transform_data
            source: WORKSPACE
          existing_cluster_id: 0403-201312-v0u48bii
        - task_key: test_silver_data
          depends_on:
            - task_key: transform_data
          notebook_task:
            notebook_path: /Repos/kapposev@outlook.com/assessment-rent-airbnb/src/tests/test_silver_transformation_extraction
            source: WORKSPACE
          existing_cluster_id: 0403-201312-v0u48bii
        - task_key: KPI_calculation
          depends_on:
            - task_key: test_silver_data
          notebook_task:
            notebook_path: /Repos/kapposev@outlook.com/assessment-rent-airbnb/src/KPI_calculation
            source: WORKSPACE
          existing_cluster_id: 0403-201312-v0u48bii
        - task_key: test_gold_data_and_final_files
          depends_on:
            - task_key: KPI_calculation
          notebook_task:
            notebook_path: /Repos/kapposev@outlook.com/assessment-rent-airbnb/src/tests/test_gold_data_final_files
            source: WORKSPACE
          existing_cluster_id: 0403-201312-v0u48bii
